Apache UIMA Java SDK Core 3.2.0

= SelectFSs

== Negative shift on bounded selections

The `shifted` operation can no longer be used to expand a selection beyond its selection boundaries. 

Consider the following example:

----
t1 = new Token(0,1)
t2 = new Token(2,3)
t3 = new Token(4,5)
t4 = new Token(6,7)
t5 = new Token(8,9)
----

In previous versions, was also possible to use a negative shift with a bounding operator such as `following`, `coveredBy`, etc. and it would call `moveToPrevious` on the internal iterator of the selection
operation, causing it to return annotations occurring before the bounds e.g.:

----
select().shifted(-1).following(t3) => {t3, t4, t5}
----

This was found to be inconsistent behavior. The iterator used for the selection (which can also be 
obtained by calling `fsIterator()`) should respect the bounds.

As of this UIMA version, using `shifted` with a negative argument in conjunction with a bounding
operator will trigger a warning in the logs and return an empty result.

----
select().shifted(-1).following(t3) => {}
select().following(t3) => {t4, t5}
----

== Backwards selection with startAt

In previous versions, the using the `moveTo` operation backwards iterators obtained through `SelectFSs`
did never ignore type priorities - even though `SelectFSs` by default should ignore them.
