package org.apache.uima.cas.impl;

import static org.junit.Assert.*;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.apache.uima.UIMAFramework;
import org.apache.uima.cas.CAS;
import org.apache.uima.resource.ResourceInitializationException;
import org.apache.uima.resource.metadata.TypeSystemDescription;
import org.apache.uima.test.junit_extension.JUnitExtension;
import org.apache.uima.util.CasCreationUtils;
import org.apache.uima.util.InvalidXMLException;
import org.apache.uima.util.XMLInputSource;
import org.junit.Test;

public class JCasCoverClassFactoryTest {

  @Test
  public void testCreateJCasCoverClass() throws InvalidXMLException, IOException, ResourceInitializationException {
    File file = JUnitExtension.getFile("JCasGen/typeSystemAllKinds.xml");
    TypeSystemDescription tsDesc = UIMAFramework.getXMLParser().parseTypeSystemDescription(
            new XMLInputSource(file));
   
    CAS cas = CasCreationUtils.createCas(tsDesc, null, null);
    
    JCasCoverClassFactory jcf = new JCasCoverClassFactory();
    
    byte[] r = jcf.createJCasCoverClass((TypeImpl) cas.getTypeSystem().getType("pkg.sample.name.All"));

    Path root = Paths.get(".");  // should resolve to the project path
    Path dir = root.resolve("temp/test/JCasGen");
    dir.toFile().mkdirs();
    Files.write(dir.resolve("testOutputAllKinds.class"), r);
    
    System.out.println("debug: generated byte array");
  }

}
