// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements. See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership. The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied. See the License for the
// specific language governing permissions and limitations
// under the License.

[[ugr.issues]]
= Known Issues

*JCasGen merge facility only supports Java levels 1.4 or earlier*::
JCasGen has a facility to merge in user (hand-coded) changes with the code generated by JCasGen.
This merging supports Java 1.4 constructs only.
JCasGen generates Java 1.4  compliant code, so as long as any code you change here also only uses Java 1.4 constructs, the  merge will work, even if you're using Java 5 or later.
If you use syntactic structures particular to Java 5 or later, the merge operation will likely fail to merge properly.

*Descriptor editor in Eclipse tooling does not work with libgcj 4.1.2*::
The descriptor editor in the Eclipse tooling does not work with libgcj 4.1.2, and possibly other versions of libgcj.
This is apparently due to a bug in the implementation of their XML library, which results in a class cast error.
libgcj is used as the default JVM for Eclipse in Ubuntu (and other Linux distributions?).  The workaround is to use a different JVM to start Eclipse.